name: Tests
on:
 pull_request:
   branches: [main]
 push:
   branches: [main]
jobs:
  incompat:
    name: Test Incompatibilities
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - name: Test Incompatibilities 3.0
        run: sbt '++3.0.0; incompat-30 / test; ++2.13.6; incompat-30 / test'
      - name: Test Incompatibilities 3.1
        run: sbt 'incompat-31 / test'
  tutorials:
    name: Check Tutorials
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - name: Sbt Migration Tutorial
        run: sbt '++3.0.0; sbt-migration-tutorial / run; ++2.13.6; sbt-migration-tutorial / run'
      - name: Macro Cross-Building
        run: sbt '++3.0.0; macro-cross-building-example / test; ++2.13.6; macro-cross-building-example / test'
      - name: Macro Mixing
        run: sbt '++3.0.0; macro-mixing-example-test / test; ++2.13.6; macro-mixing-example-test / test'
